export default function PrivacyPage() {
  return (
    <div style={{ maxWidth: '900px', margin: '0 auto', padding: '60px 20px', fontFamily: 'system-ui, -apple-system, sans-serif', lineHeight: '1.8', color: '#333' }}>
      <h1 style={{ textAlign: 'center', fontSize: '36px', fontWeight: 'bold', marginBottom: '10px', textTransform: 'uppercase', letterSpacing: '1px' }}>Privacy Policy</h1>
      <p style={{ textAlign: 'center', color: '#666', marginBottom: '50px', fontSize: '14px' }}>Last modified: January 4, 2026</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>1. Introduction</h2>
      <p style={{ marginBottom: '15px' }}>Please read this Privacy Policy before using our Service including the Website and API (collectively, the "Service"). This Privacy Policy governs the types of information and data we collect and how we use and share this information. Your access to and use of the Service are available for your use only on the condition that you agree to the Terms of Service available at https://384866.xyz/terms.</p>
      <p style={{ marginBottom: '15px' }}>Prompt Optimizer ("Company") operates the Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>2. Definitions</h2>
      <p style={{ marginBottom: '10px' }}><strong>API</strong> - Prompt Optimizer application programming interface to be integrated with the User's software.</p>
      <p style={{ marginBottom: '10px' }}><strong>Cookies</strong> - Small files stored on your Device.</p>
      <p style={{ marginBottom: '10px' }}><strong>Device</strong> - A computer or a mobile device.</p>
      <p style={{ marginBottom: '10px' }}><strong>Personal Data</strong> - Data about a living individual who can be identified from those data.</p>
      <p style={{ marginBottom: '10px' }}><strong>Service</strong> - Together the Website and/or the API.</p>
      <p style={{ marginBottom: '10px' }}><strong>Usage Data</strong> - Data collected automatically either generated by the use of Service or from Service infrastructure itself.</p>
      <p style={{ marginBottom: '10px' }}><strong>User</strong> - The individual using our Service.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>3. Information Collection and Use</h2>
      <p style={{ marginBottom: '15px' }}>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>4. Types of Data Collected</h2>
      
      <h3 style={{ fontSize: '20px', fontWeight: 'bold', marginTop: '25px', marginBottom: '12px' }}>Personal Data</h3>
      <p style={{ marginBottom: '12px' }}>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you, including:</p>
      <ul style={{ marginLeft: '30px', marginBottom: '15px' }}>
        <li style={{ marginBottom: '8px' }}>Email address</li>
        <li style={{ marginBottom: '8px' }}>First name and last name</li>
        <li style={{ marginBottom: '8px' }}>Cookies and Usage Data</li>
      </ul>

      <h3 style={{ fontSize: '20px', fontWeight: 'bold', marginTop: '25px', marginBottom: '12px' }}>Usage Data</h3>
      <p style={{ marginBottom: '15px' }}>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a Device. This Usage Data may include information such as your computer's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique Device identifiers, and other diagnostic data.</p>

      <h3 style={{ fontSize: '20px', fontWeight: 'bold', marginTop: '25px', marginBottom: '12px' }}>Tracking Cookies Data</h3>
      <p style={{ marginBottom: '12px' }}>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Examples of Cookies we use:</p>
      <ul style={{ marginLeft: '30px', marginBottom: '15px' }}>
        <li style={{ marginBottom: '8px' }}><strong>Session Cookies</strong> - We use Session Cookies to operate our Service</li>
        <li style={{ marginBottom: '8px' }}><strong>Preference Cookies</strong> - We use Preference Cookies to remember your preferences and various settings</li>
        <li style={{ marginBottom: '8px' }}><strong>Security Cookies</strong> - We use Security Cookies for security purposes</li>
      </ul>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>5. Use of Data</h2>
      <p style={{ marginBottom: '12px' }}>Prompt Optimizer uses the collected Personal Data for various purposes:</p>
      <ul style={{ marginLeft: '30px', marginBottom: '15px' }}>
        <li style={{ marginBottom: '8px' }}>To provide and maintain our Service</li>
        <li style={{ marginBottom: '8px' }}>To notify you about changes to our Service</li>
        <li style={{ marginBottom: '8px' }}>To allow you to participate in interactive features of our Service when you choose to do so</li>
        <li style={{ marginBottom: '8px' }}>To provide customer support</li>
        <li style={{ marginBottom: '8px' }}>To gather analysis or valuable information so that we can improve our Service</li>
        <li style={{ marginBottom: '8px' }}>To monitor the usage of our Service</li>
        <li style={{ marginBottom: '8px' }}>To detect, prevent and address technical issues</li>
      </ul>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>6. Retention of Data</h2>
      <p style={{ marginBottom: '15px' }}>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>7. Transfer of Data</h2>
      <p style={{ marginBottom: '15px' }}>Your information, including Personal Data, may be transferred to and maintained on computers located outside of your jurisdiction where the data protection laws may differ. The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>8. Disclosure of Data</h2>
      <p style={{ marginBottom: '15px' }}>We may disclose Personal Data you provide under certain circumstances, if required to do so by law or in response to valid requests by public authorities.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>9. Security of Data</h2>
      <p style={{ marginBottom: '15px' }}>The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>10. Service Providers</h2>
      <p style={{ marginBottom: '15px' }}>We may employ third-party companies and individuals to facilitate our Service, provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>11. Payments</h2>
      <p style={{ marginBottom: '15px' }}>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g., Creem). We will not store or collect your payment card details.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>12. Links to Other Sites</h2>
      <p style={{ marginBottom: '15px' }}>Our Service may contain links to other sites that are not operated by us. We strongly advise you to review the Privacy Policy of every site you visit.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>13. Children's Privacy</h2>
      <p style={{ marginBottom: '15px' }}>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>14. Changes to This Privacy Policy</h2>
      <p style={{ marginBottom: '15px' }}>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last modified" date at the top of this page.</p>

      <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginTop: '40px', marginBottom: '15px', borderBottom: '2px solid #333', paddingBottom: '8px' }}>15. Contact Us</h2>
      <p style={{ marginBottom: '8px' }}>If you have any questions about this Privacy Policy, please contact us:</p>
      <p style={{ marginBottom: '15px' }}><strong>Email:</strong> support@384866.xyz</p>
    </div>
  );
}
